version: '3'

services:
  nginx:
    depends_on:
      - wordpress
      - mariadb
    build: requirements/nginx
    container_name: nginx
    environment:
      USER_LOGIN: "${USER_LOGIN}"
      WP_NAME: "wordpress"
      WP_PORT: "9000"
    restart: always
    networks:
      - network
    ports:
      - "443:443"
    volumes:
      - wp:/var/www/html

  wordpress:
    depends_on:
      - mariadb
    build: requirements/wordpress
    container_name: wordpress
    restart: always
    environment:
      USER_LOGIN: "${USER_LOGIN}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_DB_HOST: "mariadb"
      MARIADB_HOST_PORT: "3306"
      WORDPRESS_REGULAR_USER: "${WORDPRESS_REGULAR_USER}"
      WORDPRESS_REGULAR_USER_PASS: "${WORDPRESS_REGULAR_USER_PASS}"
      WORDPRESS_REGULAR_USER_EMAIL: "${WORDPRESS_REGULAR_USER_EMAIL}"
      WORDPRESS_PRIVILEDGED_USER: "${WORDPRESS_PRIVILEDGED_USER}"
      WORDPRESS_PRIVILEDGED_USER_PASS: "${WORDPRESS_PRIVILEDGED_USER_PASS}"
      WORDPRESS_PRIVILEDGED_USER_EMAIL: "${WORDPRESS_PRIVILEDGED_USER_EMAIL}"
    networks:
      - network
    volumes:
      - wp:/var/www/html

  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    environment:
      USER_LOGIN: "${USER_LOGIN}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      DB_NAME: "${DB_NAME}"
      WORDPRESS_IP: "wordpress"
    restart: always
    networks:
      - network
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
    driver: local
    driver_opts:
      device: /home/${USER_LOGIN}/data/db
      type: none
      o: bind
  wp:
    driver: local
    driver_opts:
      device: /home/${USER_LOGIN}/data/wp
      type: none
      o: bind

networks:
  network: