version: '3'

services:
  nginx:
    depends_on:
      - mariadb
      - wordpress
    build: requirements/nginx
    container_name: nginx
    environment:
      USER_LOGIN: "${USER_LOGIN}"
      WP_NAME: "${WP_NAME}"
      WP_IP: "${WP_PORT}"
    restart: always
    networks:
      - network
    ports:
      - "443:443"
    volumes:
      - wp:/var/www/html

  wordpress:
    depends_on:
      - mariadb
    build: requirements/wordpress
    container_name: wordpress
    restart: always
    environment:
      USER_LOGIN: "${USER_LOGIN}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_DB_HOST: "${DB_HOST_IP}"
      MARIADB_HOST_PORT: "${DB_HOST_PORT}" 
    networks:
      - network
    volumes:
      - wp:/var/www/html

  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    environment:
      USER_LOGIN: "${USER_LOGIN}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_NAME: "${DB_NAME}"
      WORDPRESS_IP: "${WP_NAME}"
    restart: always
    networks:
      - network
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
    driver: local
    driver_opts:
      device: /home/${USER_LOGIN}/data/db
      type: none
      o: bind
  wp:
    driver: local
    driver_opts:
      device: /home/${USER_LOGIN}/data/wp
      type: none
      o: bind

networks:
  network: